feat(pace-19): add retention to rulesets for filtering rows
getstrm/pace pull request #50
Opened 2023-11-14 14:24 UTC by bobvandenhoogen

2023-11-14 14:35 UTC, ivan-p92 commented on protos/getstrm/pace/api/entities/v1alpha/entities.proto
> +        Period period = 2;
What about principals who may see all data? Is that simply configured by omitting the period?

2023-11-14 14:35 UTC, ivan-p92 commented on protos/getstrm/pace/api/entities/v1alpha/entities.proto
> +        int64 days = 1;
Days should be ok for now, and otherwise we can add more fine-grained (or coarser) units.

2023-11-14 14:35 UTC, ivan-p92 commented on protos/getstrm/pace/api/entities/v1alpha/entities.proto
> +    repeated Retention retention = 4;
Why is Retention repeated?

2023-11-14 14:37 UTC, bobvandenhoogen commented on protos/getstrm/pace/api/entities/v1alpha/entities.proto
> +    repeated Retention retention = 4;
I could see multiple date columns in a dataset each defining a different retention period

2023-11-14 14:38 UTC, bobvandenhoogen commented on protos/getstrm/pace/api/entities/v1alpha/entities.proto
> +        Period period = 2;
I thought so, empty period equals infinite retention period

2023-11-14 14:39 UTC, bobvandenhoogen commented on protos/getstrm/pace/api/entities/v1alpha/entities.proto
> +        int64 days = 1;
Exactly my thought, therefore a separate message `Period`

2023-11-14 14:41 UTC, bobvandenhoogen commented on protos/getstrm/pace/api/entities/v1alpha/entities.proto
> +        Period period = 2;
but that would be an implementation detail

2023-11-14 20:11 UTC, trietsch commented on protos/getstrm/pace/api/entities/v1alpha/entities.proto
> +        int64 days = 1;
If you'd like to make this open for future variants of `Period`, better wrap it in a `oneof`.

2023-11-14 20:11 UTC, trietsch commented on protos/getstrm/pace/api/entities/v1alpha/entities.proto
> +    repeated Retention retentions = 4;
I may misunderstand the purpose, though this feels like an almost exact duplicate of what `Filters` are meant to do. Why not extend `Filters`? If the ultimate goal is to filter out the entire record / row for both `Filters` and `Retentions`, then we should reconsider the API design.

2023-11-15 09:32 UTC, bobvandenhoogen commented on protos/getstrm/pace/api/entities/v1alpha/entities.proto
> +        int64 days = 1;
disagree, I would make it a period with for example days and years populated, not a `oneof`

2023-11-15 13:55 UTC, trietsch requested changes

2023-11-15 13:55 UTC, trietsch commented on app/src/main/kotlin/com/getstrm/pace/processing_platforms/ProcessingPlatformViewGenerator.kt
> +            field("{0} + INTERVAL {1} < current_timestamp", Boolean::class.java, DSL.unquotedName(field.fullName()), inline("${this.period.days} days"))
Any idea whether `x + INTERVAL x days` is supported on all platforms?

2023-11-15 13:55 UTC, trietsch commented on protos/getstrm/pace/api/entities/v1alpha/entities.proto
> +        RetentionFilter retention_filter = 1;
Please add a validation that requires oneof to be present.

2023-11-15 13:55 UTC, trietsch commented on protos/getstrm/pace/api/entities/v1alpha/entities.proto
> +      message RetentionFilter {
Did you check all fields for possible validations?

2023-11-15 13:55 UTC, trietsch commented on app/src/test/kotlin/com/getstrm/pace/service/DataPolicyValidatorServiceTest.kt
> +    - generic_filter:
The `examples` directory also needs to be updated, but please wait for my changes to be merged for the docs.

2023-11-15 13:55 UTC, trietsch commented on app/src/main/kotlin/com/getstrm/pace/processing_platforms/bigquery/BigQueryViewGenerator.kt
> +            DSL.field("TIMESTAMP_ADD({0}, INTERVAL {1} DAY) < CURRENT_TIMESTAMP()", Boolean::class.java,  DSL.unquotedName(field.fullName()), this.period.days)
Does jooq offer a specific `DSL.timestamp_add`? This would respect differences in SQL dialects (we'd only benefit from ANSI vs Postgres there, but still).

2023-11-15 14:00 UTC, bobvandenhoogen commented on app/src/main/kotlin/com/getstrm/pace/processing_platforms/ProcessingPlatformViewGenerator.kt
> +            field("{0} + INTERVAL {1} < current_timestamp", Boolean::class.java, DSL.unquotedName(field.fullName()), inline("${this.period.days} days"))
All but one, BigQuery. Hence the open fun that is overridden for BQ.

2023-11-15 15:57 UTC, bobvandenhoogen commented on app/src/main/kotlin/com/getstrm/pace/processing_platforms/bigquery/BigQueryViewGenerator.kt
> +            DSL.field("TIMESTAMP_ADD({0}, INTERVAL {1} DAY) < CURRENT_TIMESTAMP()", Boolean::class.java,  DSL.unquotedName(field.fullName()), this.period.days)
added

2023-11-15 17:02 UTC, merged