feat(pace-52): add EvaluateDataPolicy RPC
getstrm/pace pull request #68
Opened 2023-11-21 11:55 UTC by ivan-p92

2023-11-21 12:12 UTC, trietsch requested changes

2023-11-21 12:12 UTC, trietsch commented on protos/getstrm/pace/api/data_policies/v1alpha/data_policies.proto
> +      post: "/data-policies/evaluate"
I'd change this in `/data-policies/{data_policy_id}/evaluate` with the rest of the fields as body.

2023-11-21 12:12 UTC, trietsch commented on protos/getstrm/pace/api/data_policies/v1alpha/data_policies.proto
> +  entities.v1alpha.DataPolicy data_policy = 1;
This is a message instead of an id since you also want to provide a full data policy that should be evaluated (i.e. one that has not been persisted yet)?

2023-11-21 12:12 UTC, trietsch commented on protos/getstrm/pace/api/data_policies/v1alpha/data_policies.proto
> +  string data_sample = 2;
As you already mentioned in chat, making this repeated and an explicit message is a better way IMO, as the client should parse the CSV into the correct format.
In order to be future proof (as in, we might also want to evaluate a single transform), you could also decide to wrap this in a `oneof`, as follows:
```protobuf
oneof evaluate {
  string data_sample = 1;
  // in the future, we might add:
  EvaluateTransform transform = 2;
}
```

Where:
```protobuf
message EvaluateTransform {
  string field_name = 1;
  string input = 2;
  string principal = 3;
}
```

2023-11-21 12:12 UTC, trietsch commented on protos/getstrm/pace/api/data_policies/v1alpha/data_policies.proto
> +    // The result of the evaluation in CSV format, including headers.
If you decide to go with the `oneof`, then the comment regarding CSV should be updated.

2023-11-21 12:45 UTC, ivan-p92 commented on protos/getstrm/pace/api/data_policies/v1alpha/data_policies.proto
> +      post: "/data-policies/evaluate"
But the policy doesn't necessarily exist yet, thus may not have an ID yet, right?

2023-11-21 12:45 UTC, ivan-p92 commented on protos/getstrm/pace/api/data_policies/v1alpha/data_policies.proto
> +  entities.v1alpha.DataPolicy data_policy = 1;
Yes, exactly.

2023-11-24 09:23 UTC, trietsch reviewed
Awesome work, looks neat! A few comments.

2023-11-24 09:23 UTC, trietsch commented on app/src/main/kotlin/com/getstrm/pace/processing_platforms/h2/H2Transformer.kt
> +                "regexp_substr({0}, {1})",
Does jooq offer explicit functions for the two regex actions denoted here? If so, we could also override the `regexReplace` fun with these. We'd benefit over static type checking, instead of the `DSL.val`.

2023-11-24 09:23 UTC, trietsch commented on app/src/main/kotlin/com/getstrm/pace/service/DataPolicyEvaluationService.kt
> +        val principalsToEvaluate = dataPolicy.ruleSetsList.first().uniquePrincipals() + null
Why not iterate over all rule sets?

2023-11-24 09:23 UTC, trietsch commented on protos/getstrm/pace/api/data_policies/v1alpha/data_policies.proto
> +  // and nested fields are not supported.
We should validate and reject such a request in the API layer (maybe this is possible through proto validations, but I don't think that's desirable).

2023-11-24 09:23 UTC, trietsch commented on protos/getstrm/pace/api/data_policies/v1alpha/data_policies.proto
> +  oneof sample_data {
Sorry to bring this up so late in the dev process, but I'd prefer to rename this field to `evaluation`. If we want to add support for evaluating single transforms with specific input for an existing data policy, it'd fit better.
The `csv` field could also be renamed to `sample_csv` if you'd like.

2023-11-24 10:14 UTC, ivan-p92 commented on protos/getstrm/pace/api/data_policies/v1alpha/data_policies.proto
> +  // and nested fields are not supported.
At the moment, there will simply be an jooq exception, I think that suffices? Seems overly complex to check if the policy is standard-sql only? I will improve the error message for incompatible statements, I hadn't covered that yet.

2023-11-24 10:15 UTC, ivan-p92 commented on app/src/main/kotlin/com/getstrm/pace/service/DataPolicyEvaluationService.kt
> +        val principalsToEvaluate = dataPolicy.ruleSetsList.first().uniquePrincipals() + null
Ok, yeah let's do that. I wanted to keep it simple at first from an input perspective, but we don't actually need more than one input.

2023-11-24 10:17 UTC, ivan-p92 commented on app/src/main/kotlin/com/getstrm/pace/processing_platforms/h2/H2Transformer.kt
> +                "regexp_substr({0}, {1})",
Nope. I don't see the issue with the vals though? The end result is the same as with the `regexp_replace_all` function of jooq. I will change the `unquotedName` stuff to `DSL.field(field.fullName(), String::class.java` in all transformers though.

2023-11-24 10:19 UTC, ivan-p92 commented on protos/getstrm/pace/api/data_policies/v1alpha/data_policies.proto
> +  oneof sample_data {
I find `evaluation` a strange name for a one of that's supposed to contain sample input. Also, to support evaluating a single transform, I'd rather create a new call that doesn't require a data policy to have been upserted already. E.g. just provide the transform itself and input value(s). What do you think?

2023-11-24 12:41 UTC, trietsch commented on app/src/main/kotlin/com/getstrm/pace/processing_platforms/h2/H2Transformer.kt
> +                "regexp_substr({0}, {1})",
A `DSL.field` with a custom function does not do any type checking IIRC, that's why I said this.

2023-11-24 12:42 UTC, trietsch commented on protos/getstrm/pace/api/data_policies/v1alpha/data_policies.proto
> +  // and nested fields are not supported.
What I was pointing at, is that we should provide a warning to the end user, that we cannot render any results for e.g. `SqlStatement`, and that it should be ignored when creating the actual SQL.

2023-11-24 12:44 UTC, trietsch commented on protos/getstrm/pace/api/data_policies/v1alpha/data_policies.proto
> +  oneof sample_data {
If that's the case and you don't want to be able to add `EvaluateTransform` here in the `oneof`, then why did we make this a `oneof` in the first place? Yes, `sample_data` could be fetched / provided in/from different locations / formats, though I was thinking more towards making this API also compatible with single transform evaluations.

2023-11-24 12:45 UTC, trietsch commented on protos/getstrm/pace/api/data_policies/v1alpha/data_policies.proto
> +  oneof sample_data {
We also don't know what the workflow is. When someone wants to evaluate a single transform, does that person create a draft data policy in the first place? Or does that person want to evaluate a transform in place and not store the policy yet?

2023-11-24 13:02 UTC, ivan-p92 commented on protos/getstrm/pace/api/data_policies/v1alpha/data_policies.proto
> +  // and nested fields are not supported.
We can render anything that's standard sql, so not accepting `SqlStatement` seems a bit too much to me.

2023-11-24 15:03 UTC, ivan-p92 commented on app/src/main/kotlin/com/getstrm/pace/processing_platforms/h2/H2Transformer.kt
> +                "regexp_substr({0}, {1})",
We agreed not to make any further changes, we have #28 for additional checks.

2023-11-24 15:04 UTC, ivan-p92 commented on protos/getstrm/pace/api/data_policies/v1alpha/data_policies.proto
> +  // and nested fields are not supported.
We improved the error details in case of a sql exception.

2023-11-24 15:04 UTC, ivan-p92 commented on protos/getstrm/pace/api/data_policies/v1alpha/data_policies.proto
> +  oneof sample_data {
We made it more future-proof by means of one-ofs.

2023-11-25 11:02 UTC, merged